name: Smart Borrow System
version: "1.0"
slug: smart-borrow
description: Borrow system for Home Assistant

startup: services
boot: auto

panel_icon: mdi:archive
panel_title: Borrow System

host_network: true

ports:
  8099/tcp: 8099

webui: "http://[HOST]:[PORT:8099]"

arch:
  - amd64
  - aarch64
  - armv7

init: false