name: "Smart Borrow System"
version: "1.0"
slug: "smart_borrow"
description: "Borrow system for Home Assistant"
startup: "services"
boot: "auto"
host_network: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Backend API"